#!/usr/bin/env python3

"""
ALIGaToR                  /^^^^\\
             /^^\\________/0     \\
            (                    `~+++,,_____,,++~^^^^^^^
          ...V^V^V^V^V^V^\\...............................
             Allen Mullen


ALIGaToR is the Annotator of Loci for IG and T-cell Receptor. It uses known annotations
	of an IG/TR genomic region and extrapolates those to new set of genomic contigs.

Usage: 
	aligator <command> [ <args>... ]

Commands:

	extract    Extract reference annotations from a (downloaded) IMGT webpage 
	predict    Predict RSS in genomic sequences
	annotate   Use reference annotations and predicted RSS to annotate novel genomic sequences

Created by Chaim A Schramm and Simone Olubo on 2024-04-15.
Updates for predictRSS by CASchramm on 2024-11-14.

Copyright (c) 2024-2025 Vaccine Research Center, National Institutes of Health, USA.
All rights reserved.

"""

import os, re, sys
from docopt import docopt
from subprocess import run

if __name__ == '__main__':

	SOURCE_DIR = os.environ.get('ALIGATOR_PATH', "")
	if not os.path.exists( SOURCE_DIR ):
		find_path = re.match("(.+)/aligator", sys.argv[0])
		if find_path:
			SOURCE_DIR = find_path.group(1)
		else:
			sys.exit( "Can't find the code directory, please set ALIGATOR_PATH environmental variable." )

	args = docopt( __doc__, options_first=True )

	#log command line
	sys.path.append(f"{SOURCE_DIR}/..")
	from aligator import logCmdLine
	logCmdLine(sys.argv)

	if args['<command>'] == 'extract':
		run(['python', f"{SOURCE_DIR}/IMGThtmlParser.py"] + args['<args>'])
 
	elif args['<command>'] == 'predict':
		predict_doc = """predictRSS.sh

This script uses the DnaGrep application (Merelli et al NAR 2010) to predict the presence
	of Recombination Signal Sequences (RSS) using the Recombination Information Content (RIC)
	developed by Cowell et al (Genome Biol 2002). It is part of the ALIGaToR immunogenetic
	annotation suite.

Usage: predictRSS.sh FASTA OUT [ --species HS --min12 <num> --min23 <num> ]

Options:
   FASTA           Fasta file to predict
   OUT             Header for output files
   --species HS    Species for prediction model. Only HS and MM are
                       recognized [default: HS]
   --min12 <num>   Minimum RIC for an RSS12 [default: -38.81]
   --min23 <num>   Minimum RIC for an RSS23 [default: -58.85]

Output will be in BED format with names OUT.RSS12.bed and OUT.RSS23.bed

Created by Chaim A Schramm on 2024-04-15.
Tweaked RSS23 threshold slightly (seems to be a typo in the RSSsite 
    online docs) by CA Schramm 2024-10-09.
Added option to use mouse model and custom thresholds by CASchramm 2024-11-14

Copyright (c) 2024 Vaccine Research Center, National Institutes of Health, USA.
All rights reserved."""
		newargs = docopt( predict_doc, argv=args['<args>'] )
		run(['bash', f"{SOURCE_DIR}/predictRSS.sh", SOURCE_DIR, newargs['FASTA'], newargs['OUT'], newargs['--species'], newargs['--min12'], newargs['--min23']] )

	elif args['<command>'] == 'annotate':
		run(['python', f"{SOURCE_DIR}/annotator.py"] + args['<args>'])

	elif args['<command>'] in ['help', None]:
		run(['python', f"{SOURCE_DIR}/aligator", '--help'])

	else:
		exit("ALIGaToR does not recognize the command %r. Please see 'aligator help'." % args['<command>'])
